### ISSUE TITLE
java.lang.IllegalArgumentException: Component class com.jkl.apertain.util.APertainBroadcastReceiver does not exist in com.packagename

### ISSUE THREAD

**Issue by krunalindrodiya** [jkltech/apertain-sdk-lib#1]
java.lang.IllegalArgumentException: Component class com.jkl.apertain.util.APertainBroadcastReceiver does not exist in com.packagename
    at android.os.Parcel.readException(Parcel.java:1624)
    at android.os.Parcel.readException(Parcel.java:1573)
    at android.content.pm.IPackageManager$Stub$Proxy.setComponentEnabledSetting(IPackageManager.java:4031)
    at android.app.ApplicationPackageManager.setComponentEnabledSetting(ApplicationPackageManager.java:1860)
    at com.jkl.apertain.fcm.NotificationEventReceiver.setAlarm(NotificationEventReceiver.java:80)
    at com.jkl.apertain.ApertainFactory.init(ApertainFactory.java:172)
    at packagename.activityname.onCreate(activityname.java:35)
    at android.app.Activity.performCreate(Activity.java:6251)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
    at android.app.ActivityThread.-wrap11(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5417)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by jkltech** [comment]
Resolved as invalid package name mentioned in the Manifest file.
